// Generated by wrangler types
// Manually declared for development — run `pnpm cf-typegen` to regenerate

interface Env {
  AI: Ai;
  VECTORIZE: VectorizeIndex;
  CHUNKS_KV: KVNamespace;
  MCP_OBJECT: DurableObjectNamespace;
  API_AUTH_TOKEN: string;
}
